### ISSUE TITLE
FEATURE: Enable pinning hidden [.*] content during a deploy

### ISSUE THREAD

**Issue by andyschwab** [ipfs-shipyard/ipfs-dns-deploy#16]
I'd like to deploy a `.well-known` subdirectory, which is currently skipped because the default is to ignore hidden files.

One possible solution is to add a forth, optional argument to https://github.com/ipfs-shipyard/ipfs-dns-deploy/blob/master/scripts/pin-to-cluster.sh that appends `--hidden` in the script.

Thoughts @olizilla?

**Comment by olizilla** [comment]
ok so, i think this is the right fix to get that working https://github.com/ipfs-shipyard/ipfs-dns-deploy/pull/18

adds an `EXTRA_IPFS_CLUSTER_ARGS` env var where we can set `--hidden` and have it passed to the call to `ipfs-cluster-ctl`... here is proof of life; a copy of the ipfs website, added to cluster via this PR with the hidden dir included: https://bafybeigblukzcyouhgzxpzmys2btaplcopczoqr3iwb73a7chtny2zhglu.ipfs.dweb.link/.well-known
