### ISSUE TITLE
Rebuild docker container with IPFS_CLUSTER=0.10.0-rc1

### ISSUE THREAD

**Issue by hsanjuan** [ipfs-shipyard/ipfs-dns-deploy#3]
I have just released 0.10.0-rc1 and, unfortunately, API brings some breaking changes that the older clients will have trouble with (I think). The dokcer container should provide `ipfs-cluster-ctl` from version 0.10.0-rc1

**Comment by olizilla** [comment]
@hsanjuan thanks for the heads up. Have you rolled out `0.10.0-rc1` to cluster.ipfs.io already? If not, how long have I got?

**Comment by hsanjuan** [comment]
@olizilla yes, rolled out. But, funny enough the /add responses did not change because I forgot to do something and things keep working as before. They probably should change for the stable release because now it is unconsistent. I'll ping you before next deployment and coordinate it with you.

**Comment by olizilla** [comment]
@hsanjuan I just got round to trying out the new image with `ipfs-cluster-ctl` `0.10.0` and I'm seeing a new runtime error when calling add

```
$ docker run -it olizilla/ipfs-dns-deploy
$ pin-to-cluster.sh test /tmp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c4c80]

goroutine 34 [running]:
main.main.func6.1(0xc000026eb4, 0xc00047a140, 0xc0000a8840)
	github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-ctl/main.go:436 +0x320
created by main.main.func6
	github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-ctl/main.go:417 +0x60f
```

...all that changed here was I bumped the verison number to `0.10.0` see: https://github.com/ipfs-shipyard/ipfs-dns-deploy/commit/41f751d886472b75726db34904d19e555cd23531

**Comment by hsanjuan** [comment]
It's because I haven't deployed 0.10.0 still. It will work once that's done. We just need to agree on a good moment to switch.

**Comment by olizilla** [comment]
Superceeded by #5
